import { ChangeEvent, useRef } from 'react';
import { Bell, Check, Database, Download, HardDrive, MoonStar, RotateCcw, ShieldCheck, Upload } from 'lucide-react';
import { useQuestStore } from '../store/useQuestStore';
import type { Accent, AppData } from '../types';
import { Panel, SectionHeader } from '../components/ui/Primitives';

export function Settings() {
  const { data, setPreference, importData } = useQuestStore();
  const fileRef = useRef<HTMLInputElement>(null);
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `codequest-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const restore = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)) as AppData; if (!parsed.languages || !parsed.topics || !parsed.sessions) throw new Error(); importData(parsed); } catch { window.alert('That file is not a valid CodeQuest backup.'); } }; reader.readAsText(file); event.target.value = ''; };
  const accents: { id: Accent; name: string; colors: string[] }[] = [{ id: 'cyan', name: 'Astral cyan', colors: ['#5ee7f7', '#7874f2'] }, { id: 'violet', name: 'Arcane violet', colors: ['#a78bfa', '#ec8ff1'] }, { id: 'amber', name: 'Solar amber', colors: ['#ffd166', '#ff8e72'] }, { id: 'mint', name: 'Verdant mint', colors: ['#63e6be', '#5ed5e7'] }];

  return <div className="page-stack settings-page">
    <div className="settings-grid">
      <Panel className="settings-card"><SectionHeader title="Realm appearance" kicker="Dark themes only" action={<MoonStar size={19} />} /><p>Choose the energy that flows through your interface.</p><div className="accent-grid">{accents.map((accent) => <button key={accent.id} className={data.preferences.accent === accent.id ? 'active' : ''} onClick={() => setPreference('accent', accent.id)}><span>{accent.colors.map((color) => <i key={color} style={{ background: color }} />)}</span><strong>{accent.name}</strong>{data.preferences.accent === accent.id && <Check size={13} />}</button>)}</div><label className="toggle-row"><span><strong>Reduced motion</strong><small>Quiet the drifting particles and transitions.</small></span><input type="checkbox" checked={data.preferences.compactMotion} onChange={(event) => setPreference('compactMotion', event.target.checked)} /><i /></label></Panel>
      <Panel className="settings-card"><SectionHeader title="Gentle signals" kicker="Notifications" action={<Bell size={19} />} /><p>Useful reminders, never pressure.</p><label className="toggle-row"><span><strong>Session reminders</strong><small>Nudge you when a planned focus window begins.</small></span><input type="checkbox" checked={data.preferences.notifications} onChange={(event) => setPreference('notifications', event.target.checked)} /><i /></label><label className="toggle-row"><span><strong>Revision whispers</strong><small>Surface knowledge nodes ready for revisiting.</small></span><input type="checkbox" checked={data.preferences.revisionReminders} onChange={(event) => setPreference('revisionReminders', event.target.checked)} /><i /></label></Panel>
      <Panel className="settings-card data-settings"><SectionHeader title="Your local archive" kicker="Backup & restore" action={<Database size={19} />} /><div className="privacy-callout"><ShieldCheck size={19} /><div><strong>Nothing leaves this machine</strong><p>Your realms, notes, sessions, and history live in a private SQLite database inside the CodeQuest app data folder.</p></div></div><div className="data-actions"><button className="primary" onClick={exportData}><Download size={16} />Create backup</button><button className="secondary" onClick={() => fileRef.current?.click()}><Upload size={16} />Restore backup</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={restore} /></div><div className="db-location"><HardDrive size={16} /><span><small>Desktop database</small><strong>codequest.db</strong></span><em>Healthy</em></div></Panel>
      <Panel className="settings-card"><SectionHeader title="Data portability" kicker="Export your journey" action={<RotateCcw size={19} />} /><p>Take a readable copy of your journey whenever you like. JSON exports include every local entity.</p><button className="secondary full-button" onClick={exportData}><Download size={16} />Export all journey data</button><div className="storage-meter"><span>Local storage used <strong>~184 KB</strong></span><i><b /></i><small>SQLite grows comfortably to millions of entries.</small></div></Panel>
    </div>
    <div className="settings-footer"><span className="brand-mark"><Database size={16} /></span><div><strong>CodeQuest 0.1.0</strong><small>Local-first desktop companion · no accounts · no cloud</small></div><span>Made for the long journey.</span></div>
  </div>;
}
